openapi: 3.0.4
info:
  title: Subdomain Finder
  description: Subdomain Finder is a simple tool for finding all the available subdomains for a given domain. It returns a list of all the available subdomains for the given domain.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/subdomainfinder:
    get:
      summary: Scan Subdomains
      description: Subdomain Finder is a simple tool for finding all the available subdomains for a given domain. It returns a list of all the available subdomains for the given domain.
      operationId: subdomainfinder
      parameters:
      - name: domain
        in: query
        schema:
          type: string
        required: true
        description: The domain you want to find all the available subdomains for (e.g. google.com)
        example: google.com
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  count: 54
                  rootDomain:
                    domain: paypal.com
                    records:
                    - 151.101.3.1
                    - 162.159.141.96
                    - 151.101.195.1
                  subDomains:
                  - host: smtp.paypal.com
                    records:
                    - 64.4.244.68
                  - host: ns1.paypal.com
                    records:
                    - 64.4.244.70
                  - host: www.paypal.com
                    records:
                    - 151.101.193.21
                    - 151.101.129.21
                    - 151.101.1.21
                    - 151.101.65.21
                  - host: ns2.paypal.com
                    records:
                    - 64.4.244.71
                  - host: autodiscover.paypal.com
                    records:
                    - 52.96.191.8
                    - 52.96.79.200
                    - 52.96.239.184
                    - 52.96.156.24
                  - host: test.paypal.com
                    records:
                    - 156.59.125.88
                  - host: admin.paypal.com
                    records:
                    - 173.0.88.10
                  - host: mx.paypal.com
                    records:
                    - 10.190.3.55
                  - host: m.paypal.com
                    records:
                    - 151.101.193.21
                    - 151.101.1.21
                    - 151.101.129.21
                    - 151.101.65.21
                  - host: mail.paypal.com
                    records:
                    - 159.127.187.12
                  - host: api.paypal.com
                    records:
                    - 66.211.168.123
                  - host: demo.paypal.com
                    records:
                    - 151.101.1.21
                    - 151.101.193.21
                    - 151.101.129.21
                    - 151.101.65.21
                  - host: news.paypal.com
                    records:
                    - 192.243.228.1
                  - host: stage.paypal.com
                    records:
                    - 64.4.241.16
                  - host: login.paypal.com
                    records: []
                  - host: dl.paypal.com
                    records:
                    - 216.113.188.115
                  - host: i.paypal.com
                    records:
                    - 63.140.39.240
                    - 63.140.38.55
                    - 63.140.39.72
                    - 63.140.39.35
                    - 63.140.39.22
                    - 63.140.38.210
                    - 63.140.38.138
                    - 63.140.38.111
                    - 63.140.39.117
                    - 63.140.39.15
                  - host: ssl.paypal.com
                    records:
                    - 151.101.129.21
                    - 151.101.1.21
                    - 151.101.65.21
                    - 151.101.193.21
                  - host: service.paypal.com
                    records:
                    - 192.243.228.1
                  - host: connect.paypal.com
                    records:
                    - 151.101.129.21
                    - 151.101.1.21
                    - 151.101.193.21
                    - 151.101.65.21
                  - host: sandbox.paypal.com
                    records:
                    - 151.101.195.1
                    - 151.101.3.1
                    - 162.159.141.96
                  - host: reports.paypal.com
                    records:
                    - 173.0.93.28
                  - host: t.paypal.com
                    records:
                    - 151.101.131.1
                    - 151.101.67.1
                    - 151.101.3.1
                    - 151.101.195.1
                  - host: training.paypal.com
                    records:
                    - 64.4.254.252
                  - host: status.paypal.com
                    records:
                    - 20.69.68.249
                  - host: forms.paypal.com
                    records:
                    - 216.113.190.190
                  - host: shopping.paypal.com
                    records:
                    - 208.76.140.165
                  - host: business.paypal.com
                    records:
                    - 151.101.1.21
                    - 151.101.129.21
                    - 151.101.65.21
                    - 151.101.193.21
                  - host: c.paypal.com
                    records:
                    - 151.101.129.21
                    - 151.101.1.21
                    - 151.101.65.21
                    - 151.101.193.21
                  - host: p.paypal.com
                    records:
                    - 151.101.67.1
                    - 151.101.3.1
                    - 151.101.131.1
                    - 151.101.195.1
                  - host: labs.paypal.com
                    records:
                    - 173.0.88.135
                  - host: manager.paypal.com
                    records:
                    - 173.0.93.191
                  - host: xmpp.paypal.com
                    records:
                    - 173.224.160.141
                    - 185.97.80.136
                    - 173.224.160.144
                    - 185.97.80.137
                  - host: developer.paypal.com
                    records:
                    - 151.101.65.21
                    - 151.101.1.21
                    - 151.101.193.21
                    - 151.101.129.21
                  - host: transfer.paypal.com
                    records:
                    - 151.101.129.21
                    - 151.101.1.21
                    - 151.101.193.21
                    - 151.101.65.21
                  - host: pics.paypal.com
                    records:
                    - 151.101.195.1
                    - 151.101.131.1
                    - 151.101.67.1
                    - 151.101.3.1
                  - host: accounts.paypal.com
                    records:
                    - 173.0.93.28
                  - host: mcp.paypal.com
                    records:
                    - 104.18.7.170
                    - 104.18.6.170
                  - host: history.paypal.com
                    records:
                    - 151.101.193.21
                    - 151.101.1.21
                    - 151.101.129.21
                    - 151.101.65.21
                  - host: registration.paypal.com
                    records:
                    - 173.0.93.135
                  - host: bm.paypal.com
                    records:
                    - 130.211.16.153
                  - host: hotspot.paypal.com
                    records:
                    - 64.4.240.12
                  - host: rms.paypal.com
                    records:
                    - 173.0.82.166
                  - host: cb.paypal.com
                    records:
                    - 173.0.88.142
                  - host: sip2.paypal.com
                    records:
                    - 64.68.79.227
                  - host: credit.paypal.com
                    records:
                    - 159.127.187.12
                  - host: smtp-in.paypal.com
                    records:
                    - 64.4.244.68
                  - host: solutions.paypal.com
                    records:
                    - 173.0.88.143
                  - host: emails.paypal.com
                    records:
                    - 13.111.204.15
                  - host: notify.paypal.com
                    records:
                    - 173.0.81.33
                    - 173.0.81.65
                    - 173.0.81.140
                    - 173.0.81.1
                  - host: sip1.paypal.com
                    records:
                    - 64.68.79.226
                  - host: gadget.paypal.com
                    records:
                    - 173.0.94.17
                  - host: av2.paypal.com
                    records:
                    - 64.68.79.231
                  - host: av1.paypal.com
                    records:
                    - 64.68.79.230
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
