openapi: 3.0.4
info:
  title: Subdomain Finder
  description: >-
    Subdomain Finder is a simple tool for finding all the available subdomains
    for a given domain. It returns a list of all the available subdomains for
    the given domain.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/subdomainfinder:
    get:
      summary: Scan Subdomains
      description: >-
        Subdomain Finder is a simple tool for finding all the available
        subdomains for a given domain. It returns a list of all the available
        subdomains for the given domain.
      operationId: subdomainfinder
      parameters:
        - name: domain
          in: query
          schema:
            type: string
          required: true
          description: >-
            The domain you want to find all the available subdomains for (e.g.
            google.com)
          example: google.com
        - name: limit
          in: query
          schema:
            type: integer
          required: false
          description: Limit the number of subdomains to detect
          example: 5
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  rootDomain:
                    domain: paypal.com
                    records:
                      - 151.101.3.1
                      - 151.101.195.1
                      - 162.159.141.96
                  subDomains:
                    - host: api.paypal.com
                      records:
                        - 66.211.168.123
                    - host: mail.paypal.com
                      records:
                        - 159.127.187.12
                    - host: admin.paypal.com
                      records:
                        - 173.0.88.10
                    - host: smtp.paypal.com
                      records:
                        - 64.4.244.68
                    - host: ns2.paypal.com
                      records:
                        - 64.4.244.71
                    - host: test.paypal.com
                      records:
                        - 156.59.125.88
                    - host: ns1.paypal.com
                      records:
                        - 64.4.244.70
                    - host: mx.paypal.com
                      records:
                        - 10.190.3.55
                    - host: demo.paypal.com
                      records:
                        - 151.101.1.21
                        - 151.101.193.21
                        - 151.101.129.21
                        - 151.101.65.21
                    - host: shop.paypal.com
                      records:
                        - 54.148.26.111
                        - 35.80.170.143
                        - 54.212.145.128
                    - host: www.paypal.com
                      records:
                        - 151.101.193.21
                        - 151.101.65.21
                        - 151.101.129.21
                        - 151.101.1.21
                    - host: m.paypal.com
                      records:
                        - 151.101.129.21
                        - 151.101.1.21
                        - 151.101.193.21
                        - 151.101.65.21
                    - host: stage.paypal.com
                      records:
                        - 64.4.241.16
                    - host: ssl.paypal.com
                      records:
                        - 151.101.65.21
                        - 151.101.129.21
                        - 151.101.193.21
                        - 151.101.1.21
                    - host: i.paypal.com
                      records:
                        - 63.140.38.107
                        - 63.140.39.244
                        - 63.140.39.114
                        - 63.140.38.116
                        - 63.140.39.254
                        - 63.140.39.146
                        - 63.140.38.213
                        - 63.140.39.214
                        - 63.140.39.87
                        - 63.140.39.123
                    - host: news.paypal.com
                      records:
                        - 192.243.228.1
                    - host: autodiscover.paypal.com
                      records:
                        - 52.96.79.120
                        - 52.96.79.200
                        - 52.96.163.40
                        - 52.96.79.248
                    - host: dl.paypal.com
                      records:
                        - 216.113.188.115
                    - host: connect.paypal.com
                      records:
                        - 151.101.65.21
                        - 151.101.129.21
                        - 151.101.1.21
                        - 151.101.193.21
                    - host: sandbox.paypal.com
                      records:
                        - 151.101.195.1
                        - 162.159.141.96
                        - 151.101.3.1
                    - host: training.paypal.com
                      records:
                        - 64.4.254.252
                    - host: c.paypal.com
                      records:
                        - 151.101.129.21
                        - 151.101.65.21
                        - 151.101.193.21
                        - 151.101.1.21
                    - host: business.paypal.com
                      records:
                        - 104.18.6.168
                        - 104.18.7.168
                    - host: service.paypal.com
                      records:
                        - 192.243.228.1
                    - host: login.paypal.com
                      records: []
                    - host: t.paypal.com
                      records:
                        - 151.101.3.1
                        - 151.101.131.1
                        - 151.101.67.1
                        - 151.101.195.1
                    - host: status.paypal.com
                      records:
                        - 20.69.68.249
                    - host: shopping.paypal.com
                      records:
                        - 208.76.140.165
                    - host: newsletter.paypal.com
                      records:
                        - 192.243.228.1
                    - host: reports.paypal.com
                      records:
                        - 173.0.93.28
                    - host: forms.paypal.com
                      records:
                        - 216.113.190.190
                    - host: labs.paypal.com
                      records:
                        - 173.0.88.135
                    - host: p.paypal.com
                      records:
                        - 151.101.131.1
                        - 151.101.67.1
                        - 151.101.195.1
                        - 151.101.3.1
                    - host: transfer.paypal.com
                      records:
                        - 151.101.193.21
                        - 151.101.129.21
                        - 151.101.65.21
                        - 151.101.1.21
                    - host: xmpp.paypal.com
                      records:
                        - 173.224.160.144
                        - 173.224.160.141
                        - 185.97.80.137
                        - 185.97.80.136
                    - host: manager.paypal.com
                      records:
                        - 173.0.93.191
                    - host: developer.paypal.com
                      records:
                        - 151.101.1.21
                        - 151.101.193.21
                        - 151.101.129.21
                        - 151.101.65.21
                    - host: account.paypal.com
                      records:
                        - 192.243.228.1
                    - host: history.paypal.com
                      records:
                        - 151.101.129.21
                        - 151.101.193.21
                        - 151.101.65.21
                        - 151.101.1.21
                    - host: pics.paypal.com
                      records:
                        - 151.101.131.1
                        - 151.101.195.1
                        - 151.101.67.1
                        - 151.101.3.1
                    - host: registration.paypal.com
                      records:
                        - 173.0.93.135
                    - host: mcp.paypal.com
                      records:
                        - 104.18.7.170
                        - 104.18.6.170
                    - host: accounts.paypal.com
                      records:
                        - 173.0.93.28
                    - host: hotspot.paypal.com
                      records:
                        - 64.4.240.12
                    - host: bm.paypal.com
                      records:
                        - 130.211.16.153
                    - host: rms.paypal.com
                      records:
                        - 173.0.82.166
                    - host: cb.paypal.com
                      records:
                        - 173.0.88.142
                  count: 47
                  totalFound: 47
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
